[package]
name = "memorious-desktop"
version = "0.1.0"
description = "Infinite Journal desktop"
edition = "2021"
license.workspace = true

[lib]
name = "memorious_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
anyhow = "1"
memorious-core = { path = "../../../crates/core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
log = "0.4"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tauri = { version = "2.11.3", features = ["test"] }
tempfile = "3"
image = "0.25"
